config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/regions', to: 'index#regions', as: 'regions'
  get '/make_wine',to: 'index#make_wine'
  get '/bottle',to: 'index#bottle'
  get '/order_status',to: 'index#order_status'
  get '/how_works',to: 'index#how_works'
  get '/faqs',to: 'index#faqs'
  get '/mobile_solution',to: 'index#mobile_solution'
  get '/enterprise',to: 'index#enterprise'
  get '/ui_ux',to: 'index#ui_ux'
  get '/contact_us',to: 'index#contact_us'


  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories, dependent: :destroy
	validates :name, presence: true, uniqueness: true	
end

app/models/company.rb
class Company < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :category, presence: true
	validates :city, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/firmware_image.rb
class FirmwareImage < ApplicationRecord
end

app/models/grape.rb
class Grape < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/models/ip.rb
class Ip < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/wine.rb
class Wine < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/index_helper.rb
module IndexHelper
	
	def modal_text company
		modal_text = Category.find(company.category).name unless company.category.nil?
		modal_text = SubCategory.find(company.subcategory).name unless company.subcategory.nil?
		return modal_text
	end

	def position ( n, m )
		position = {}
		divmod = n.divmod m
		position[:top] = divmod[1] % 2 != 0 ? divmod[0] * 270  : ( 2 * divmod[0] + 1 ) * 135 
		position[:left] = divmod[1] * 235.5
		return position
	end

	def search_result_height length
		divmod = length.divmod 4
		height = ( divmod[0] + 1 ) * 270 if divmod[1] == 0
		height = ( divmod[0] + 2 ) * 270 unless divmod[1] == 0
		return height
	end

	def set_title title
		if title.length > 17
			new_title = title[0..14] + '...' 
		else
			new_title = title 
		end		
		return new_title
	end

	def url_code url
		code_url = url.gsub(/\s+/, "-")
		code_url = code_url.downcase!
		return code_url		
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/index/about.html.erb
<% provide(:title, "About Us | What We Do") %>
<% provide(:body_class, "about-us-page") %>

<!--Learn More About Us Section-->
<section class="learn-more-about-us-section">
  <div class="container-fluid no-padding">
    <div class="banner-container sf">
      <div class="container">
        <div class="row">
          <h1 class="title-container col-xs-12 col-sm-12 col-lg-12">
            <div class="city-name">About Us</div>
            <div class="qoute-container col-xs-12 col-sm-12 col-lg-12">Learn More About US</div>
          </h1>
        </div>
        <div class="row">
        </div>
      </div>
    </div>
  </div>
</section>
<!--End of Learn More-->

<section class="info-about-us-section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 info-text-container blogtextreapt">
        <div class="blog_hed no-padding">
          <h3>
            <%= @detail.try(:title) %>
          </h3>
        </div>

        <p>
          <%= @detail.try(:description) %>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/index/contact.html.erb
<% provide(:title, "CONTACT") %>
<% provide(:body_class, "about-us-page") %>

<section class="contact-section">
	<div class="container">
		<div class="contact-us">
			<h1>Contact Us</h1>
			<%= image_tag 'inbox.png', class: 'inbox-img' %>
			<p><!-- Thank you for contacting 10 Best Design. For submission to our directory, plesae submit your site on the approciate U.S. stae's page in our Web Development Directory. For other inquires, questions, or comments, plesase use the from below. --></p>
			<a class="contact-arrow btn btn-primary" > Contact Form </a>
		</div>		
	</div>
</section>
<section>
	<div id="contact-map">
	</div>
	<script type="text/javascript">
                  function initialize() {
                        var mapCanvas = document.getElementById('contact-map');
                        var mapOptions = {
                            center: new google.maps.LatLng(51.4804346, -0.10958000000005086),
                            zoom: 17,
                            scrollwheel: false,
						    navigationControl: false,
						    mapTypeControl: false,
						    scaleControl: false,
						    draggable: false
                        };
                        var map = new google.maps.Map(mapCanvas, mapOptions);
                        var icon = "<%= asset_path('icon-google-map.png') %>";
                        var pointMarker = new google.maps.Marker({
                            position: new google.maps.LatLng(51.4804346, -0.10958000000005086),
                            map: map,
                            icon: icon
                        });
                    }
                    // google.maps.event.addDomListener(window, 'load', initialize);
                </script>
                <script async defer src="<%= Rails.application.secrets[:google_map_url] %>key=<%= Rails.application.secrets[:google_map_key] %>&callback=initialize" type="text/javascript"></script>
</section>
<section>
	<div class="container contact-form">
		<div>
			<h1>Send an Email</h1>
			<%= form_for( :contact, method: 'get', remote: true ) do |f| %>
				<div id = "email-alert"></div>			
				<%= f.email_field :email, class: 'form-control', placeholder: 'Your Email', required: true %>
				<%= f.text_field :name, class: 'form-control', placeholder: 'Your Name', required: true %>
				<%= f.text_area :message, class: 'form-control', placeholder: 'Your Message', rows: 10, required: true %>
				<%= f.button '<span class="glyphicon glyphicon-envelope"></span>'.html_safe, class: 'btn btn-primary btn-block' %>
			<% end %>
		</div>
	</div>	
</section>
<!--Our partners section-->
<section class="our-partners-section">
    <div class="container">    	
        <div class="row">
            <div class="col-md-12 title-container"><div>our partners</div></div>
            <ul class="partners-list">
                <li><%= image_tag 'icons-partner-1.png' %></li>
                <li><%= image_tag 'icons-partner-2.png' %></li>
                <li><%= image_tag 'icons-partner-3.png' %></li>
                <li><%= image_tag 'icons-partner-4.png' %></li>
                <li><%= image_tag 'icons-partner-5.png' %></li>
                <li><%= image_tag 'icons-partner-6.png' %></li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12 become-partner-container">
                <div class="text-container">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                    velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
                </div>
                <div class="button-container">
                    <a href="#">BECOME A PARTNER <span class="arrow">&#8594</span></a>
                </div>
            </div>
        </div>
    </div>
</section>

<!--end of our partners section-->

app/views/index/contact.js.erb
$('#email-alert').html("<strong><%= @result %>!</strong><%= @result %> to send email...").fadeIn(1000).fadeOut(1000);

app/views/index/enterprise.html.erb
<section class="make_wine">
    <div class="container-fluid footer_link_bg">
        <div class="container">    
        <h1> Enterprise </h1>
        </div>
    </div>
</section>
<!-- End of banner  -->
<section class="make_wine_content">
<div class="container">

<div class="col-md-12">
    <div class="inner_text_make_wine">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
            standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled
            it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic
            typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.
        </p>
        
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
            standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled
            it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic
            typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset
            sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
            PageMaker including versions of Lorem Ipsum.
        </p>

    </div>


</div>


</section>

app/views/index/home.html.erb
<% provide(:title, "Grapedia") %>
  <% provide(:body_class, " ") %>
    <!--Start Search Section-->
    <section class="search-section">
      <div class="container-fluid background-image san-franc">
        <div class="container">
          <div>
            <div class="heading-container col-centered col-md-12 col-sm-12 col-xs-12 col-lg-12">
              <span class="wow pulse wow_pulse" data-wow-duration="0.15">Search our grape and wine list</span>
            </div>
          </div>
          <div>
            <div class="search-field-container col-md-12 col-sm-12 col-xs-12 col-lg-12">
              <%= form_for(:search_form, url:search_path, :method => 'get') do |f| %>
                <div class="search-wrapper">
                  <span class="search_icon"></span>
                  <%= text_field_tag :search, '', placeholder: "Search by name", class:"search_field_input" %>
                    <select name="search_select" id="search_select">
                      <option>Wine</option>
                      <option>Grape</option>
                    </select>
                    <%= f.submit 'Search', class: "search_button sf" %>
                </div>
                <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- <div class="container-fluid city-explore-container">
      <div class="container">
        <div>
          <div class="ready-to-explore-container">
            <div class="text-container col-centered col-md-8 col-xs-12 col-lg-8 col-sm-12">
              <div class="question-container">Ready to Explore the Grape?</div>
              <div class="guide-container">Download Our Best of Wind Guide</div>
              <div class="link-container"><a class="sf" href="#"></a></div>
            </div>
          </div>
        </div>
      </div> -->

      </div>
    </section>

    <!--Places Section-->
    <section class="places-section">
      <div class="container">
        <div class="wine">
          <div class="col-md-6 wine_inner wine_visibi ">
            <div class="week">
              <%= link_to '', wine_week_path, class: 'place-link' %>
                <div class="icons text-center">
                  <img src="/assets/glass.png" width="23%" alt="">
                  <h3>WINE OF THE WEEK</h3>
                  <p class="text-center">Lorem Ipsum is simply dummy text
                    <br> of the printing and typesetting industry</p>
                </div>
            </div>
          </div>
          <div class="col-md-6 wine_visibi">
            <div class="week">
              <%= link_to '', grape_week_path, class: 'place-link' %>
                <div class="icons text-center">
                  <img src="/assets/grape.png" width="16%" alt="">
                  <h3>GRAPES OF THE WEEK</h3>
                  <p class="text-center">Lorem Ipsum is simply dummy text
                    <br> of the printing and typesetting industry</p>
                </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="intro-section">
      <div class="container">
        <div class="col-sm-12">
          <div class="heading text-center ">
            <h2>Introduction</h2>
          </div>
        </div>
      </div>
      <div class="container started_filling halfgraybg ">
        <div class="container ">

          <div class="col-md-6 col-sm-12 col-xs-12 inner_textp ">
            <div class="inner text-info-container ">
              <p>We have started filling our grape guide with Italian grapes, our friends at Italyabroad.com are helping us.
                Only Italy grows more than 1000 grapes and I will take us some time before we can list all of them and then
                move to the next country, so please be patient For each grape you will find information on where the grape
                is grown, its history and characteristics and pairing suggestions and for each grape you will also find wines
                from different suppliers made with the grape. At the bottom of the page you will also see a comment form
                and please feel free to get in touch if you think we have forgotten something.</p>
            </div>
          </div>

          <div class="col-md-6 col-sm-12 col-xs-12 icons_col ">
            <div>
              <div class="icons_bar ">
                <div class="icon_img ">
                  <img src="assets/icon.png " alt=" ">
                </div>
                <div class="contentdivicon ">We started as a grape guide but then, thanks to your comments and feedbacks, we decided to add a wine library</div>
              </div>
            </div>
            <div>
              <div class="icons_bar contentdiviconmidgap ">
                <div class="icon_img ">
                  <img src="assets/icon2.png " alt=" ">
                </div>
                <div class="contentdivicon ">With regard to Italian wines, the first thing to say is the wine classifications </div>
              </div>
            </div>
            <div>
              <div class="icons_bar ">
                <div class="icon_img ">
                  <img src="assets/icon3.png " alt=" ">
                </div>
                <div class="contentdivicon ">Wine are classified into DOCG, DOC, IGT and table wine. DOCG ......, DOC....., IGT....... and table wine........</div>
              </div>
            </div>
          </div>



        </div>
      </div>

    </section>


    <!--End we make it easy section-->

    <!--Feature Section-->
    <section class="feature-section ">
      <div class="container-fluid img-wrapper ">
        <div class="image-container ">
          <div class="info-container ">
            <div class="container ">
              <div class=" ">
                <div class="col-md-7 blackoverlay ">
                  <div class="category-container ">Grapedia</div>
                  <div class="title-container ">Best Grape & Wines</div>

                  <div class="text-container ">Ever wonder how wine is made? Or why some bottles of wine are more expensive than others? Here's some information
                    for you to better understand wine and what makes its cost
                  </div>
                  <div class="button-container ">
                    <div class="read-more-container ">
                      <a href="# ">READ MORE</a>
                    </div>
                    <div class="social-container ">
                      <ul class="social-list ">
                        <li class="share-button ">
                          <a href="# "></a>
                        </li>
                        <li class="like-button ">
                          <a href="# "></a>
                        </li>
                        <li class="chat-container ">
                          <a href="# "></a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
    <!--End of Feature Section-->

    <!--Learn More Section  -->
    <section class="learn-more-section ">
      <div class="container">
        <div class="col-sm-12">
          <div class="heading text-center">
            <h2>Cheap vs. Expensiv</h2>
          </div>
        </div>
      </div>
      <div class="container started_filling halfwhitebg marbot100px">
        <div class="container mobnopadd">
          <div class="col-md-6 col-sm-12 col-xs-12 inner_textp mobpadd15px">
            <div class="progress-container">
              <ul class="progress-list">
                <li class="progress-item ">
                  <div class="icon-expert sf"></div>
                  <div class="progress-name-container">EXPERT OPINIONS</div>
                  <div class="progress-bar-wrapper">
                    <div class="progress-bar progress_inner sf" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">
                      30%
                    </div>
                  </div>
                </li>
                <li class="progress-item ">
                  <div class="icon-awards sf"></div>
                  <div class="progress-name-container">PREVIOUS ACCOLADES</div>
                  <div class="progress-bar-wrapper">
                    <div class="progress-bar progress_inner1 sf" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                      20%
                    </div>
                  </div>
                </li>
                <li class="progress-item ">
                  <div class="icon-phone sf"></div>
                  <div class="progress-name-container">OTHER DATA & STATS</div>
                  <div class="progress-bar-wrapper">
                    <div class="progress-bar progress_inner2 sf" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
                      50%
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-md-6 col-sm-12 col-xs-12 inner_textp  inner_para mobpadd15px">
            <div class="inner text-info-container why_are">
              <p>
                <strong>So</strong> why are some wines cheap, and others are more expensive? Cheap wines are stock-picked from the
                vineyards and processed by machinery. The grapes are often damaged or require large amounts of pesticides
                to help keep rot and decay at bay. Many preservatives are added, lowering sanitation standards and decreasing
                production costs. When you purchase a cheap bottle of wine, you are paying for pesticides, preservatives,
                and low quality grapes.
              </p>
            </div>
          </div>

        </div>
      </div>
    </section>
    <!--End Learn More Section-->
    <!--Media section-->
    <!--End of Media section-->
    <!--City Guide Section-->

    <!--End of city guide -->

app/views/index/like_up.js.erb
$('#like-text-<%= @company.id %>').text("<%= @like %>");

app/views/index/regions.html.erb
<% provide(:title, "Regions Page") %>
  <% provide(:body_class, "regions-page") %>
    <section class="region_section">

    <div class="container-fluid no-padding">
    <div class="banner-container region_banner">
        <div class="container">
            <div class="row">

            <div class="category-title col-xs-12 col-sm-12 col-lg-12">
            <span class="separator" style="margin-left: 20px;" >Top Regions |</span>
            <span class="date-container "></span>
        </div>
        <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">Regions</h1>
    </div>

            </div>
        </div>
    </div>
</div>

    </section>
<!--region_country-->

<section class="learn-more-section">
        <div class="container mobnopadd listdetail">
            <div class="col-md-6 col-sm-12 col-xs-12  inner_textp mobpadd15px">
                <img src="assets/regions_sidehead.jpg" class="img-responsive" width="100%">
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12 milano_para">
                <div class="inner text-info-container">
                    <p>
                      <%= @region_detail.try(:description) %>
                    </p>
                    <div class="col-md-12 region_bg">
                    <ul>
              <% @regions && @regions.each do |region| %>
                <li class="col-sm-6 col-sm-6 col-xs-4">
              
                    <p>
                      <%= region %>
                    </p>
                  
    
                </li>
                <% end %>
                </ul>
            </div>
                </div>
              
            </div>
        </div>
    </section>

    <section class="regins_col">
    <div class="container">
    <div class="col-md-12 regins_col_head">
<div class="bortop1px"></div>
            <div class="col-md-6 regins_col_head">
                  <h3>Grapes</h3>
                  <div class="col-sm-6 nopadd">
                  <img class="img-responsive" src="/assets/grapes_head.jpg" alt="">  </div>
                  <div class="col-sm-6">
                  
                  <p><strong><%= @grape_detail.try(:name) %></strong></p>
                    <p class="readmoretext">
                      <%= @grape_detail.try(:long_des) %> 
                    </p>
                    <%= link_to "Read More", grapes_path %>
                  </div>
         
                </div>
                <div class="col-md-6 regins_col_head">
                    <h3> <%= @about_detail.try(:title) %> </h3>

                    <div class="col-sm-6 nopadd">
                    <img class="img-responsive" src="/assets/about_head.jpg" alt=""> 
                    </div>
                    <div class="col-sm-6">
                    <p class="readmoretext">
                        <%= @about_detail.try(:description) %>  </p>
                        <%= link_to "Read More", about_path %>
                    
                    </div>
                </div>


    <div class="col-md-12 from_our_blog">
    <h3> <%= @blog_detail.try(:title) %> </h3>
    <div class="col-sm-4 nopadd">
      <%= image_tag "/uploads/" + @blog_detail.pic , class: 'img-responsive', alt: @blog_detail.pic %>
    </div>
    <div class="col-sm-8">
      <p>
        <%= @blog_detail.try(:des) %> <%= link_to "Read More", blogs_path %>
      </p>
    </div>
        </div>
       
        
        </div>
    </div>
</section>

app/views/index/share_up.js.erb
$('#share-text-<%= @company.id %>').text("<%= @share %>");

app/views/layouts/_footer.html.erb
<!--Footer Start-->
<footer>
	<div class="container">
		<div class="">
			<div class="col-md-4 col-xs-12 col-sm-12 bottom_logo inner_textp ">
				<a href="">
					<img src="assets/bottom_logo.png" width="80%" alt=""> </a>
				<p>
					<a href="">
						<b>NEWS LETTER</b>
					</a>
				</p>
				<div class="join-wrapper">
					<input class="newsletter_input" placeholder="Enter Email" type="email">
					<button class="">Join</button>
				</div>
				<!-- <form action="#">
					<div class="form-group">
						<input type="email" class="form-control" placeholder="Enter Email" id="email">
						<button class="join-button sf">Join</button>
					</div>
				</form>  -->
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12 inner_textp ">
				<div class="list">
					<p>
						<b>
							<a href="#">CUSTOMER SERVICES </a>
						</b>
					</p>
					<ul>
						<li>
							<%= link_to "Wine of the week", wine_week_path %>
						</li>
						<li>
							<%= link_to "Grape of the week",grape_week_path %>
						</li>
						<li>
							<%= link_to " How to make wine",make_wine_path %>
						</li>
						<li>
							<%= link_to "What is your bottle",bottle_path %>
						</li>
						<li>
							<%= link_to "Order Status",order_status_path %>
						</li>
						<li>
							<%= link_to "How It Works",how_works_path %>
						</li>
            <li>
              <%= link_to "Contact Us",contact_us_path %>
            </li>
					</ul>
				</div>
			</div>
			<div class="col-md-2 col-xs-12 col-sm-12 inner_textp ">
				<div class="list">
					<p>
						<b>
							<%= link_to "About",about_path %>
						</b>
					</p>
					<ul>
						<li>
							<%= link_to "FAQS",faqs_path %>
						</li>
						<li>
							<%= link_to "Mobile Solution",mobile_solution_path %>
						</li>
						<li>
							<%= link_to "Enterprise",enterprise_path %>
						</li>
						<li>
							<%= link_to "UI-UX",ui_ux_path %>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-md-3 col-xs-12 col-sm-12 inner_textp ">
				<div class="list">
					<p>
						<b>
							<a href="#">FINDS US </a>
						</b>
					</p>
					<ul class="footerlocation">
						<li class="locationlink">
							<a href="#">
								<i class="fa fa-map-marker"></i>
								<span class="lineheight18px">157 New Kent Rd, Borough, London SE1 4AG, UK </a>
						</li>
						</span>
						<li class="locationlink">
							<a href="#">
								<i class="fa fa-mobile" aria-hidden="true"></i>
								<span> (000) 123 456789 </span>
							</a>
						</li>
						<li>
							<a href="mailto:SF@Grapedia.com?Subject=Hello%20again" target="_top">
								<i class="fa fa-envelope-o" aria-hidden="true"></i>
								<span> SF@Grapedia.com </span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</footer>

<section class="bootom_footer">
	<div class="container">
		<div class="">
			<div class="col-md-6 col-xs-12 col-sm-12 ">
				<div class="copy">
					<p>
						<a href="#">Grapedia © 2018. All Rights Reserved. </a>
					</p>
				</div>
			</div>

			<div class="col-md-6 col-xs-12 col-sm-12 ">
				<div class="social_icons_bot text-right">
					<p>
						<b>
							<a href="#">CONNECT WITH US </a>
						</b>
					</p>
					<ul class="">
						<li>
							<a href="">
								<i class="fa fa-linkedin" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="">
								<i class="fa fa-facebook" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="">
								<i class="fa fa-instagram" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="">
								<i class="fa fa-google-plus" aria-hidden="true"></i>
							</a>
						</li>
						<li>
							<a href="">
								<i class="fa fa-twitter" aria-hidden="true"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
</body>

</html>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
   <%= yield %>
<%= render 'layouts/footer' %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>