config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  resources :firmware_images
  resources :wines
  resources :grapes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/home', to: 'index#home'
  get '/about', to: 'index#about', as: 'about'
  get '/grow', to: 'index#grow', as: 'grow'
  get '/contact', to: 'index#contact', as: 'contact'
  get '/top-:category/:company', to: 'index#place', as: 'place'
  get '/top-:category', to: 'index#ranking', as: 'ranking'
  get '/search', to: 'index#search', as: 'search'
  get '/shareup/:id', to: 'index#share_up', as: 'shareup'
  get '/likeup/:id', to: 'index#like_up', as: 'likeup'
  get '/regions', to: 'index#regions', as: 'regions'
  get '/make_wine',to: 'index#make_wine'
  get '/bottle',to: 'index#bottle'
  get '/order_status',to: 'index#order_status'
  get '/how_works',to: 'index#how_works'
  get '/faqs',to: 'index#faqs'
  get '/mobile_solution',to: 'index#mobile_solution'
  get '/enterprise',to: 'index#enterprise'
  get '/ui_ux',to: 'index#ui_ux'
  get '/contact_us',to: 'index#contact_us'


  get '/wines', to: 'wines#index'
  get '/wine_week', to: 'wines#week'
  get '/grape_week', to: 'grapes#week'
  get '/groups', to: 'groups#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
   resources :users
  
  scope 'admin' do
    resources :companies
  end

  root 'index#home'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :sub_categories, dependent: :destroy
	validates :name, presence: true, uniqueness: true	
end

app/models/company.rb
class Company < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	validates :category, presence: true
	validates :city, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/detail.rb
class Detail < ApplicationRecord
end

app/models/firmware_image.rb
class FirmwareImage < ApplicationRecord
end

app/models/grape.rb
class Grape < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/models/ip.rb
class Ip < ApplicationRecord
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category
  validates :name, presence: true, uniqueness: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
  	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/wine.rb
class Wine < ApplicationRecord
  scope :order_by_desc, -> { order(created_at: :desc) }
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base

	def index
    @blogs = Blog.where(publish: true)
	end
end

app/controllers/grapes_controller.rb
# grape controller
class GrapesController < InheritedResources::Base

  def index
    @about_detail = Detail.find_by(detail_type: "About")
    @blog_detail = Blog.order_by_desc.take
    @region_detail = Detail.find_by(detail_type: "Region")

    @grapes = Grape.where(publish: true)
  end

  def week
    @grapes = Grape.where(publish: true, week_pub: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/grapes_helper.rb
module GrapesHelper
end

app/helpers/index_helper.rb
module IndexHelper
	
	def modal_text company
		modal_text = Category.find(company.category).name unless company.category.nil?
		modal_text = SubCategory.find(company.subcategory).name unless company.subcategory.nil?
		return modal_text
	end

	def position ( n, m )
		position = {}
		divmod = n.divmod m
		position[:top] = divmod[1] % 2 != 0 ? divmod[0] * 270  : ( 2 * divmod[0] + 1 ) * 135 
		position[:left] = divmod[1] * 235.5
		return position
	end

	def search_result_height length
		divmod = length.divmod 4
		height = ( divmod[0] + 1 ) * 270 if divmod[1] == 0
		height = ( divmod[0] + 2 ) * 270 unless divmod[1] == 0
		return height
	end

	def set_title title
		if title.length > 17
			new_title = title[0..14] + '...' 
		else
			new_title = title 
		end		
		return new_title
	end

	def url_code url
		code_url = url.gsub(/\s+/, "-")
		code_url = code_url.downcase!
		return code_url		
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/grapes/_form.html.erb
<%= form_for(grape) do |f| %>
  <% if grape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grape.errors.count, "error") %> prohibited this grape from being saved:</h2>

      <ul>
      <% grape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :short_des %>
    <%= f.text_field :short_des %>
  </div>

  <div class="field">
    <%= f.label :logn_des %>
    <%= f.text_area :logn_des %>
  </div>

  <div class="field">
    <%= f.label :pic %>
    <%= f.text_field :pic %>
  </div>

  <div class="field">
    <%= f.label :regions %>
    <%= f.text_field :regions %>
  </div>

  <div class="field">
    <%= f.label :publish %>
    <%= f.check_box :publish %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grapes/edit.html.erb
<h1>Editing Grape</h1>

<%= render 'form', grape: @grape %>

<%= link_to 'Show', @grape %> |
<%= link_to 'Back', grapes_path %>

app/views/grapes/index.html.erb
<% provide(:body_class, "ranking-page") %>
<!--Start of Banner section-->
<section class="main-banner-section">
  <div class="container-fluid no-padding">
    <div class="banner-container">
      <div class="container">
        <div class="row">
          <div class="category-title col-xs-12 col-sm-12 col-lg-12">
            <span class="separator" style="margin-left: 20px;" >Top Blog |</span>
            <span class="date-container "><%= DateTime.now.strftime "%B %Y" %></span>
          </div>

          <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">
            Grapes
          </h1>
        </div>
      </div>
    </div>
  </div>
</section>
<!--End of Banner section-->

<section class="learn-more-section">
  <% @grapes.each_with_index do |grape, index| %>
    <div class="container mobnopadd listdetail">
      <div class="col-md-6 col-sm-12 col-xs-12  inner_textp mobpadd15px text-center paddtopbot25px">
        
          <img src="uploads/<%= grape.pic %>" class="listimgview">
       
      </div>
      <div class="col-md-6 col-sm-12 col-xs-12 milano_para">
        <div class="inner text-info-container">
          <div class="header-section">
            
            <div class="name-container">
              <div class="title-container"> <%= index+1 %> <%= set_title grape.name %></div>
            </div>
          </div>
          <span>
            <%= grape.long_des %>
          </span>
        </div>
        <div class="regins">
          <span>REGIONS : </span> 
          <% unless grape.regions == nil %>
            <span>
              <% grape.regions.split(',').each do |element| %>
                <a href="#"> <span><%= element %></span> </a>
              <% end %>
            </span>                
          <% end %>

          <span> SUPPLYER : </span> 
          <% unless grape.supply == nil %>
            <% grape.supply.split(',').each_with_index do |element,index| %>
              <a href="<%= grape.supply_url.split(',').fetch(index) %>"><%= element %>
              </a>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</section>

<section class="regins_col">
  <div class="container">
    <div class="col-md-12 regins_col_head nopadd martop30px">
      <div class="bortop1px"></div>
        <div class="col-md-6 regins_col_head">
          <h3> <%= @region_detail.try(:title) %> </h3>

          <div class="col-sm-6 nopadd">
            <img class="img-responsive" src="/assets/regions_head.jpg" alt="">
          </div>
          <div class="col-sm-6">
          <p class="readmoretext">
              <%= @region_detail.try(:description) %> </p>
              <%= link_to "Read More", regions_path %>
          </div>
        </div>

        <div class="col-md-6 regins_col_head">
          <h3> <%= @about_detail.try(:title) %> </h3>

          <div class="col-sm-6 nopadd">
            <img class="img-responsive" src="/assets/about_head.jpg" alt=""> 
          </div>
          <div class="col-sm-6">
            <p class="readmoretext">
              <%= @about_detail.try(:description) %> 
            </p>
            <%= link_to "Read More", about_path %>
          </div>
        </div>

        <div class="col-md-12 from_our_blog">
          <h3>Blog</h3>
          <div class="col-sm-4 nopadd">
            <%= image_tag "/uploads/" + @blog_detail.pic , class: 'img-responsive', alt: @blog_detail.pic %>
          </div>

          <div class="col-sm-8">
          <p><strong><%= @blog_detail.try(:title) %></strong></p>
              <p class="readmoretext">
                <%= @blog_detail.try(:des) %> <%= link_to "Read More", blogs_path %>
              </p>
              <a href="#">Read More</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/grapes/new.html.erb
<h1>New Grape</h1>

<%= render 'form', grape: @grape %>

<%= link_to 'Back', grapes_path %>

app/views/grapes/show.html.erb
<% provide(:body_class, "place-page") %>
<!--Start of banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container">
            <div class="container">
                <div class="row">
                    <div class="text-container">
                        <h1>
                            <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                                <span class="number"><%= @no %> <span class="separator"></span></span>
                                <span class="category-name"><%= @grape.name %></span>
                            </div>
                            <div class="location-wrapper col-xs-12 col-sm-12 col-lg-12">
                                <span class="location-container"><span class="location-icon"></span> </span>
                                <div class="share-container col-md-2 hidden-md hidden-lg  no-padding">
                                </div>
                            </div>
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--end of banner section-->
<div class="social-modal">
    <div class="container">
      <h1>Share</h1>
      <span class="glyphicon glyphicon-remove-circle"></span>
  </div>
</div> 
<!--Start of main info container-->
<section class="main-info-container">
    <div class="container">
        <div class="row">
            <div class="col-md-4 map-container">
                <span>
                    <%= link_to image_tag( "/uploads/" + @grape.pic, class: 'img-responsive' )%>
                </span>
            </div>
            <div class="col-md-8 text-container">
              <div class="grape-title">
                <h1 class="text-left"><%= @grape.name %></h1>
            </div>
            <div class="grape-long_description">
                <span>
                 <%= @grape.long_des %>
             </span>
            </div>
         <div class="grape-region">
             <strong class="text-info" >Regions:</strong><span style="margin-left: 14px">
                <% unless @grape.regions == nil %>
                <% @grape.regions.split(',').each do |element| %>
                <a href="#">
                  <span class="regions-element"><%=  element %></span>
                  <% end %>
              </span>
          </a>
          <% end %>
        </div>
        <div class="wine-supplyer">
         <strong class="text-info">Supplyer:</strong>
         <span style="margin-left: 14px">
            <% unless @grape.supply == nil %>
            <% @grape.supply.split(',').each_with_index do |element,index| %>
            <a href="<%= @grape.supply_url.split(',').fetch(index) %>">
              <span class="regions-element"><%=  element %></span>
              <% end %>
          </span>
        </a>
        <% end %>
        </span>
        </div>   
</div>
</div>
</div>
</section>
<!--end of main info container -->
<section class="place-slider-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12 b_slider_wrapper">
                <h1>Wine with <%= @grape.name %></h1>
                <div class="b_slider">
                    <%= image_tag 'download-1.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'download-2.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'download-3.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'download-4.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'images-wine-2.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'images-wine-3.jpg', class: 'b_slider__slide img-responsive' %>
                    <%= image_tag 'images-wine-1.jpg', class: 'b_slider__slide img-responsive' %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/grapes/week.html.erb
<% provide(:body_class, "ranking-page") %>
<!--Start of Banner section-->
<section class="main-banner-section">
    <div class="container-fluid no-padding">
        <div class="banner-container banner-container-week">
            <div class="container">
                <div class="row">
                    <div class="category-title col-xs-12 col-sm-12 col-lg-12">
                        <span class="separator">Grape of the week |</span>
                        <span class="date-container "> <%= DateTime.now.strftime "%B %Y" %></span>
                    </div>
                    <h1 class="places-container col-xs-12 col-sm-12 col-lg-12">Grape</h1>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End of Banner section-->

<!--Start of places list section-->
<section class="places-list-section">
    <% @grapes.each_with_index do |grape, index| %>
    <div class="social-modal">
        <div class="container">
          <h1>Share</h1>
          <%= social_share_button_tag(grape.name, :image => asset_path("images-places-#{index+1}.png")) %>
          <span class="glyphicon glyphicon-remove-circle"></span>
      </div>                          
  </div>
  <!--Start of place cont-->
  <div class="container-fluid no-padding">
    <div class="place-container container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-4 image-container no-padding hidden-sm hidden-xs">
                  <img src="uploads/<%= grape.pic%>" class="img-responsive">
              </div>
              <div class="col-md-8 col-sm-12 col-xs-12 info-container">
                <div class="header-section">
                    <div class="number-container"><%= index+1 %></div>
                    <div class="separator"></div>
                    <div class="name-container">
                        <div class="title-container"><strong><%= set_title grape.name %><strong></div>
                        </div>
                    </div>
                    <div class="image-for-mobile hidden-lg hidden-md">
                        <%= image_tag "public/uploads/Aglianico_del_Vulture_new.jpg", class: 'img-responsive' %>
                    </div>
                    <div class="main-text-container">
                        <p>
                          <%= grape.short_des %>
                      </p>
                  </div>
                  <div class="grape-long-description">
                    <p>
                        <%= grape.long_des %>
                    </p>
                </div>
                <div class="grape-region">
                   <strong class="text-info" >Regions:</strong><span style="margin-left: 14px">
                    <% unless grape.regions == nil %>
                    <% grape.regions.split(',').each do |element| %>
                    <a href="#">
                      <span class="regions-element "><%=  element %></span>
                      <% end %>
                  </span>
              </a>
              <% end %>
          </div>
          <div class="wine-supplyer">
           <strong class="text-info">Supplyer:</strong>
           <span style="margin-left: 14px">
            <% unless grape.supply == nil %>
            <% grape.supply.split(',').each_with_index do |element,index| %>
            <a href="<%= grape.supply_url.split(',').fetch(index) %>">
                <span class="regions-element"><%=  element %></span>
                <% end %>
            </span>
        </a>
        <% end %>
    </span>
</div>   
</div>
</div>
</div>
</div>
</div>
<!--end of place container-->                          
<% end %>    
</section>
<!--End of places list section-->
<!--google map section-->
<!-- <p id="notice"><%= notice %></p>

<h1>grapes</h1>